# Generated by Django 3.1.2 on 2020-12-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_auto_20201202_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
